name: Manage EC2 Instance with Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose an action (apply or destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  manage-infrastructure:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1 # Replace with your AWS regionn

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # Replace with the desired Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Apply or Destroy
        run: |
          if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
          elif [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            terraform plan -destroy -out=tfplan
            terraform apply -auto-approve tfplan
          else
            echo "Invalid action selected. Choose 'apply' or 'destroy'."
            exit 1
          fi
